cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      name: "\uAD00\uB9AC\uC790"
      password: $2b$12$8mdWpn1HaD.AoV3K/MALU.tUAqpqI.eMj3WkQrY6y9HJJAHOPNIOC
    yc:
      name: "\uC724\uCC3D\uC774\uC5D4\uC528"
      password: $2b$12$kgSLOb3BRjg9qfXtz4iuPu.1PYZUEudsCwFJRmGHTmqw6TIhGeZmy
preauthorized:
  emails:
  - melsby@gmail.com
